In [29]:
import pandas as pd
import numpy as ny

In [2]:
pd.__version__

'2.1.0'

In [4]:
test = pd.read_csv('housing.csv')

In [5]:
test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [6]:
missing_values = test.isna().any()

In [7]:
print(missing_values)

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool


In [9]:
unique_values_count = test['ocean_proximity'].nunique()

In [10]:
unique_values_count

5

In [12]:
filtered_test = test[test['ocean_proximity'] == 'NEAR BAY']
average_median_house_value = filtered_test['median_house_value'].mean()
print("Average median house value for 'NEAR BAY' ocean proximity:", average_median_house_value)

Average median house value for 'NEAR BAY' ocean proximity: 259212.31179039303


In [18]:
avg_test = test['total_bedrooms'].mean()
test2 = test.copy()
test2['total_bedrooms'].fillna(avg_test, inplace=True)
avg_test2 = test2['total_bedrooms'].mean()

In [14]:
avg_test

537.8705525375618

In [19]:
avg_test2

537.8705525375617

In [20]:
island = test[test['ocean_proximity'].str.contains("island", case=False, na=False)]

In [24]:
island = island[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [28]:
X = island.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [30]:
XTX = ny.dot(X.T, X)

In [31]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [32]:
inverse_XTX = ny.linalg.inv(XTX)

In [33]:
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [34]:
y = ny.array([950, 1300, 800, 1000, 1300])

In [36]:
w = ny.dot(ny.dot(inverse_XTX, X.T), y)

In [37]:
w

array([23.12330961, -1.48124183,  5.69922946])